import { ArrowUpRight, Code2 } from 'lucide-react'
import { motion } from 'framer-motion'
import { projects } from '../../data/projects'
import type { Language, Project } from '../../types'
import { SectionHeading } from '../layout/SectionHeading'
import { Badge } from '../ui/Badge'

function ProjectVisual({type}:{type:Project['visual']}) { return <div className={`project-visual ${type}`} aria-hidden="true"><div className="visual-bar"><i/><i/><i/></div>{type==='security'&&<><div className="shield">✓</div><div className="result-row"><span>SECURE</span><span>08 / 10</span></div></>}{type==='agent'&&<div className="nodes"><i/><i/><i/><i/></div>}{type==='rpg'&&<><div className="dialogue">How would you respond?</div><div className="avatar">AI</div><div className="xp">EQ +12</div></>}{type==='design'&&<><div className="phone"><i/><b/><b/></div><div className="pet">●</div></>}</div> }
export function Projects({language}:{language:Language}) { return <section id="projects" className="section"><div className="container"><SectionHeading eyebrow={language==='en'?'03 / Selected Work':'03 / Dự án Nổi bật'} title={language==='en'?'Systems designed to be useful.':'Hệ thống được thiết kế để hữu ích.'}/><div className="projects-list">{projects.map((project,i)=><motion.article initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} className="project-card" key={project.name}><ProjectVisual type={project.visual}/><div className="project-content"><span className="project-index">0{i+1}</span><p className="project-role">{project.role[language]}</p><h3>{project.name}</h3><p>{project.description[language]}</p><ul>{project.contributions.map(c=><li key={c.en}>{c[language]}</li>)}</ul><div className="badges">{project.technologies.map(t=><Badge key={t}>{t}</Badge>)}</div>{project.link&&<a className="project-link" href={project.link} target="_blank" rel="noreferrer"><Code2/>{language==='en'?'View project':'Xem dự án'}<ArrowUpRight/></a>}</div></motion.article>)}</div></div></section> }
